{
  "openapi": "3.0.3",
  "info": {
    "title": "Product Restful API",
    "description": "Documentation about product",
    "version": "1.0.0"
  },
  "paths":{
    "/categories": {
      "post": {
        "tags": ["categories"],
        "summary": "Create Category",
        "description": "",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schema/CategoryCreateUpdate"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Request Created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 201,
                  "status": true,
                  "message": "Request Created.",
                  "detail_message": {
                    "_app": "Successfully add a new category."
                  },
                  "results": null
                }
              }
            }
          },
          "400": {
            "description": "Validation Failed.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 400,
                  "status": false,
                  "message": "Validation Failed.",
                  "detail_message": {
                    "_app": "The name has already been taken."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "AccessToken": []
          }
        ]
      },
      "get": {
        "tags": ["categories"],
        "summary": "Get All Data",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Page",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "page",
            "in": "query"
          },
          {
            "required": true,
            "schema": {
              "title": "Per Page",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "per_page",
            "in": "query"
          },
          {
            "required": false,
            "schema": {
              "title": "Q",
              "minLength": 1,
              "type": "string"
            },
            "name": "q",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                    "data": [
                      {
                        "id": 1,
                        "name": "string",
                        "created_at": "2022-02-10T14:27:05.674928Z",
                        "updated_at": "2022-02-10T14:27:05.674928Z"
                      }
                    ],
                    "total": 0,
                    "next_num": null,
                    "prev_num": null,
                    "page": 1,
                    "iter_pages": []
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/categories/{category_id}": {
      "get": {
        "tags": ["categories"],
        "summary": "Get Category By Id",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "category_id",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "category_id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                    "id": 1,
                    "name": "string",
                    "created_at": "2022-04-03T22:07:32.491684Z",
                    "updated_at": "2022-04-03T22:07:32.491684Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 404,
                  "status": false,
                  "message": "Resource Not Found.",
                  "detail_message": {
                    "_app": "Category not found."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["categories"],
        "summary": "Update Category",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Category Id",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "category_id",
            "in": "path"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schema/CategoryCreateUpdate"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": {
                    "_app": "Successfully update the category."
                  },
                  "results": null
                }
              }
            }
          },
          "400": {
            "description": "Validation Failed.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 400,
                  "status": false,
                  "message": "Validation Failed.",
                  "detail_message": {
                    "_app": "The name has already been taken."
                  },
                  "results": null
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 404,
                  "status": false,
                  "message": "Resource Not Found.",
                  "detail_message": {
                    "_app": "Category not found."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "AccessToken": []
          }
        ]
      },
      "delete": {
        "tags": ["categories"],
        "summary": "Delete Category",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Category Id",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "category_id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": {
                    "_app": "Successfully delete the category."
                  },
                  "results": null
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 404,
                  "status": false,
                  "message": "Resource Not Found.",
                  "detail_message": {
                    "_app": "Category not found."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "AccessToken": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "AccessToken": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      },
      "RefreshToken": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schema": {
      "ExampleResponse": {
        "title": "ExampleResponse",
        "type": "object",
        "required": ["status_code", "status", "message"],
        "properties": {
          "status_code": {
            "title": "status_code",
            "type": "integer"
          },
          "status": {
            "title": "status",
            "type": "boolean"
          },
          "message": {
            "title": "message",
            "type": "string"
          },
          "detail_message": {
            "title": "detail_message",
            "type": "string"
          },
          "results": {
            "title": "results",
            "type": "object"
          }
        }
      },
      "CategoryCreateUpdate": {
        "title": "CategoryCreateUpdate",
        "required": ["name"],
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "maxLength": 100,
            "minLength": 3,
            "type": "string"
          }
        }
      }
    }
  }
}
