{
  "openapi": "3.0.3",
  "info": {
    "title": "Auth Restful API",
    "description": "Documentation about auth",
    "version": "1.0.0"
  },
  "paths": {
    "/auth/register": {
      "post": {
        "tags": ["auth"],
        "summary": "Register Account",
        "description": "register account and send email for verification",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schema/AuthRegister"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Request Created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 201,
                  "status": true,
                  "message": "Request Created.",
                  "detail_message": {
                    "_app": "Check your email to activated user."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/auth/confirm/{token}": {
      "get": {
        "tags": ["auth"],
        "summary": "Confirmation Token Register",
        "description": "confirm token from register and give access_token & refresh_token",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "token",
              "type": "string"
            },
            "name": "token",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                    "_app": {
                      "access_token": "string",
                      "refresh_token": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 404,
                  "status": false,
                  "message": "Resource Not Found.",
                  "detail_message": {
                    "_app": "Token not found."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/auth/resend-email": {
      "post": {
        "tags": ["auth"],
        "summary": "Resend Email",
        "description": "resend email if email not sended and give delay 5 minute",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schema/AuthResendEmail"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": {
                    "_app": "Email confirmation has send."
                  },
                  "results": null
                }
              }
            }
          },
          "400": {
            "description": "Account already activated or 5 minute delay",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 400,
                  "status": false,
                  "message": "Validation Failed.",
                  "detail_message": {
                    "_app": "string"
                  },
                  "results": null
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 404,
                  "status": false,
                  "message": "Resource Not Found.",
                  "detail_message": {
                    "_app": "Email not found."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["auth"],
        "summary": "Login User",
        "description": "create access & refresh token",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schema/AuthLogin"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                    "_app": {
                      "access_token": "string",
                      "refresh_token": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation Failed.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 400,
                  "status": false,
                  "message": "Validation Failed.",
                  "detail_message": {
                    "_app": "Please check your email to activate your account."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/auth/fresh-token": {
      "post": {
        "tags": ["auth"],
        "summary": "Fresh Token",
        "description": "",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schema/UserConfirmPassword"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                    "_app": {
                      "access_token": "string"
                    }
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "AccessToken": []
          }
        ]
      }
    },
    "/auth/refresh-token": {
      "post": {
        "tags": ["auth"],
        "summary": "Refresh Token",
        "description": "",
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                    "_app": {
                      "access_token": "string"
                    }
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "RefreshToken": []
          }
        ]
      }
    },
    "/auth/access-revoke": {
      "delete": {
        "tags": ["auth"],
        "summary": "Access Revoke",
        "description": "",
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": {
                    "_app": "An access token has revoked."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "AccessToken": []
          }
        ]
      }
    },
    "/auth/refresh-revoke": {
      "delete": {
        "tags": ["auth"],
        "summary": "Refresh Revoke",
        "description": "",
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": {
                    "_app": "An refresh token has revoked."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        },
        "security": [
          {
            "RefreshToken": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "AccessToken": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      },
      "RefreshToken": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schema": {
      "ExampleResponse": {
        "title": "ExampleResponse",
        "type": "object",
        "required": ["status_code", "status", "message"],
        "properties": {
          "status_code": {
            "title": "status_code",
            "type": "integer"
          },
          "status": {
            "title": "status",
            "type": "boolean"
          },
          "message": {
            "title": "message",
            "type": "string"
          },
          "detail_message": {
            "title": "detail_message",
            "type": "string"
          },
          "results": {
            "title": "results",
            "type": "object"
          }
        }
      },
      "AuthRegister": {
        "title": "AuthRegister",
        "required": ["email", "password", "confirm_password"],
        "type": "object",
        "properties": {
          "email": {
            "title": "Email",
            "maxLength": 100,
            "minLength": 3,
            "type": "string",
            "format": "email"
          },
          "password": {
            "title": "Password",
            "maxLength": 100,
            "minLength": 6,
            "type": "string"
          },
          "confirm_password": {
            "title": "Confirm Password",
            "maxLength": 100,
            "minLength": 6,
            "type": "string"
          }
        }
      },
      "AuthResendEmail": {
        "title": "AuthResendEmail",
        "required": ["email"],
        "type": "object",
        "properties": {
          "email": {
            "title": "Email",
            "maxLength": 100,
            "minLength": 3,
            "type": "string",
            "format": "email"
          }
        }
      },
      "AuthLogin": {
        "title": "AuthLogin",
        "required": ["email", "password"],
        "type": "object",
        "properties": {
          "email": {
            "title": "Email",
            "maxLength": 100,
            "minLength": 3,
            "type": "string",
            "format": "email"
          },
          "password": {
            "title": "Password",
            "maxLength": 100,
            "minLength": 6,
            "type": "string"
          }
        }
      },
      "UserConfirmPassword": {
        "title": "UserConfirmPassword",
        "required": ["password"],
        "type": "object",
        "properties": {
          "password": {
            "title": "Password",
            "maxLength": 100,
            "minLength": 6,
            "type": "string"
          }
        }
      }
    }
  }
}
